# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         RDF-Redland-Model-ExifTool
version:      0.03
version_from: lib/RDF/Redland/Model/ExifTool.pm
installdirs:  site
requires:
    Image::ExifTool:               0
    RDF::Redland:                  0
    Regexp::Common:                0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
